name: Publish GHCR Image
on:
  release: 
    types: [published]

  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghtoken_product_demo

jobs:
  build_container:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build Container image
        run: docker build . --tag $IMAGE_NAME
  
  push_to_registry:
    name: Push Docker image to Github Container Registry
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    needs: [build_container]
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.run.id }}
          docker push $IMAGE_ID