name: Publish DockerHub Image
on:
  release: 
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build Container image
        run: docker build . --file Dockerfile

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: stackbuilders/openfaas-haskell

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: jurisfutura/openfaas-haskell:${{ github.event.release.tag_name }}
      #     labels: ${{ steps.meta.outputs.labels }}
